<a href="https://colab.research.google.com/github/sompattanaik/Data-Science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
income = np.array([1200,1400,1500])
income

array([1200, 1400, 1500])

In [ ]:
income1 = [1200,1400,1500]
income1

[1200, 1400, 1500]

In [ ]:
income_4 = income*0.4
income_4

array([480., 560., 600.])

In [ ]:
income_5 = income*5
income_5

array([6000, 7000, 7500])

In [ ]:
inc1 = income1*0.3
inc1

TypeError: can't multiply sequence by non-int of type 'float'

In [ ]:
a = np.array([12,14,16],[15,17,19])
a

TypeError: Field elements must be 2- or 3-tuples, got '15'

In [ ]:
a = np.array([[12,14,16],[15,17,19]])
a

array([[12, 14, 16],
       [15, 17, 19]])

In [ ]:
b = np.array([[12,14,16],[15,17]])
b

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
l1 = [1,3,4,5]
l2 = [9,0,7]

In [ ]:
l1+l2

[1, 3, 4, 5, 9, 0, 7]

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [ ]:
arr1 + arr2

array([5, 7, 9])

In [ ]:
z = np.array([1,2,4])

In [ ]:
z.shape

(3,)

In [ ]:
z.size

3

In [ ]:
z.ndim

1

In [ ]:
y = np.array([[2,3],[3,5]])


In [ ]:
y.shape

(2, 2)

In [ ]:
y.size

4

In [ ]:
y.ndim

2

In [ ]:
import numpy as np
a = np.ones((3,4),dtype=np.int32)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [ ]:
b = np.arange(10,40)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [ ]:
a = np.random.random(20)
a

array([0.69811072, 0.84562072, 0.88984924, 0.29523303, 0.25769122,
       0.45435609, 0.13397797, 0.09774696, 0.65898045, 0.85120456,
       0.35442473, 0.56236774, 0.91375234, 0.0770751 , 0.53170412,
       0.14702338, 0.24493343, 0.33180136, 0.6164609 , 0.34447715])

In [ ]:
b = a.reshape(2,10)

In [ ]:
b


array([[0.69811072, 0.84562072, 0.88984924, 0.29523303, 0.25769122,
        0.45435609, 0.13397797, 0.09774696, 0.65898045, 0.85120456],
       [0.35442473, 0.56236774, 0.91375234, 0.0770751 , 0.53170412,
        0.14702338, 0.24493343, 0.33180136, 0.6164609 , 0.34447715]])

In [ ]:
c = a.reshape(5,4)

In [ ]:
c

array([[0.69811072, 0.84562072, 0.88984924, 0.29523303],
       [0.25769122, 0.45435609, 0.13397797, 0.09774696],
       [0.65898045, 0.85120456, 0.35442473, 0.56236774],
       [0.91375234, 0.0770751 , 0.53170412, 0.14702338],
       [0.24493343, 0.33180136, 0.6164609 , 0.34447715]])

In [ ]:
c.max(axis=0)

array([0.91375234, 0.85120456, 0.88984924, 0.56236774])

In [ ]:
c.max(axis = 1)

array([0.88984924, 0.45435609, 0.85120456, 0.91375234, 0.6164609 ])

In [ ]:
a = np.linspace(0,1,50)

In [ ]:
a

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [ ]:
a.reshape(25,2)

array([[0.        , 0.02040816],
       [0.04081633, 0.06122449],
       [0.08163265, 0.10204082],
       [0.12244898, 0.14285714],
       [0.16326531, 0.18367347],
       [0.20408163, 0.2244898 ],
       [0.24489796, 0.26530612],
       [0.28571429, 0.30612245],
       [0.32653061, 0.34693878],
       [0.36734694, 0.3877551 ],
       [0.40816327, 0.42857143],
       [0.44897959, 0.46938776],
       [0.48979592, 0.51020408],
       [0.53061224, 0.55102041],
       [0.57142857, 0.59183673],
       [0.6122449 , 0.63265306],
       [0.65306122, 0.67346939],
       [0.69387755, 0.71428571],
       [0.73469388, 0.75510204],
       [0.7755102 , 0.79591837],
       [0.81632653, 0.83673469],
       [0.85714286, 0.87755102],
       [0.89795918, 0.91836735],
       [0.93877551, 0.95918367],
       [0.97959184, 1.        ]])

In [ ]:
a = np.array([[12,8],[35,6]])

In [ ]:
a

array([[12,  8],
       [35,  6]])

In [ ]:
b = np.sort(a,axis=1)
b

array([[ 8, 12],
       [ 6, 35]])

In [ ]:
c = np.sort(a,axis = 0)
c

array([[12,  6],
       [35,  8]])

In [ ]:
a = np.array([[12,8],[35,6]])

In [ ]:
b = np.array([[16,38],[89,65]])

In [ ]:
a

array([[12,  8],
       [35,  6]])

In [ ]:
b

array([[16, 38],
       [89, 65]])

In [ ]:
c = np.concatenate((a,b),axis = 1)

In [ ]:
c

array([[12,  8, 16, 38],
       [35,  6, 89, 65]])

In [ ]:
d = np.concatenate((a,b),axis = 0)

In [ ]:
d

array([[12,  8],
       [35,  6],
       [16, 38],
       [89, 65]])